// Mocks generated by Mockito 5.4.5 from annotations
// in inteliteacher/test/repositories/ai/ai_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:inteliteacher/data/repositories/ai/ai_repository.dart' as _i2;
import 'package:inteliteacher/model/entities/class_plans/class_plan_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:result_dart/result_dart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i2.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultDart<_i5.CreateClassPlanRequest, Exception>>
  generateClassPlan({required String? prompt}) =>
      (super.noSuchMethod(
            Invocation.method(#generateClassPlan, [], {#prompt: prompt}),
            returnValue: _i3.Future<
              _i4.ResultDart<_i5.CreateClassPlanRequest, Exception>
            >.value(
              _i6.dummyValue<
                _i4.ResultDart<_i5.CreateClassPlanRequest, Exception>
              >(
                this,
                Invocation.method(#generateClassPlan, [], {#prompt: prompt}),
              ),
            ),
          )
          as _i3.Future<_i4.ResultDart<_i5.CreateClassPlanRequest, Exception>>);
}
